### PR TITLE
Enh accelerate tests

### PR DESCRIPTION
**Pull request by zaccharieramzi**
This also reactivates train mode model consistency tests that were deactivated by mistake

### CODE REVIEW

**Review by tomMoral — APPROVED** [review]
LGTM! Just a suggestion to make the code easier to read.

**Comment by zaccharieramzi** [comment]
@tomMoral the main problem with this proposal PR is that it doesn't work for now... I have no idea why (didn't investigate properly).

Also, the NN stuff doesn't accelerate the tests, but it has the benefit of making them clearer.

**Comment by zaccharieramzi** [comment]
Just making this about mamba, now that we are doing registration in https://github.com/benchopt/benchmark_resnet_classif/pull/22

**Comment by zaccharieramzi** [comment]
Don't know why this is failing in the current state...

**Comment by zaccharieramzi** [comment]
So apparently mamba is failing to create an environment (see [this piece of logs](https://github.com/benchopt/benchmark_resnet_classif/runs/6388317251?check_suite_focus=true#step:6:518)), but difficult to know why. @tomMoral have you seen this somewhere else?

**Pull request merged**
